openapi: 3.0.0
info:
  title: Your API Title
  version: '1.0.0'
  description: |
    This is a description of your API.
  contact:
    name: Your Name
    email: your.email@example.com
servers:
  - url: 'https://api.yourdomain.com/v1'
paths:
  /endpoint1:
    get:
      summary: Description of the endpoint kk
      operationId: getEndpoint1
      tags:
        - YourTag
      parameters:
        - name: parameter1
          in: query
          description: Description of the parameter
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/YourSchema'
  /endpoint2:
    post:
      summary: Description of the endpoint
      operationId: postEndpoint2
      tags:
        - YourTag
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/YourRequestSchema'
      responses:
        '201':
          description: Resource created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/YourResponseSchema'
components:
  schemas:
    YourSchema:
      type: object
      properties:
        attribute1:
          type: string
        attribute2:
          type: integer
  responses:
    YourResponse:
      description: Your response description
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/YourResponseSchema'
  parameters:
    YourParameter:
      name: YourParameterName
      in: query
      required: true
      schema:
        type: string
  securitySchemes:
    YourApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
security:
  - YourApiKeyAuth: []
tags:
  - name: YourTag
    description: Description of the tag
externalDocs:
  description: Additional documentation
  url: 'https://docs.yourdomain.com/api'
